spring.application.name=MarvellousFullStack
server.port=9090
spring.data.mongodb.uri=mongodb://localhost:27017/MarvellousFullStackX

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nagesh04@gmail.com
spring.mail.password=maegvbvfoemlfthy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000